assets_path: /srv/datasets/gibson2/data/assets
cubicasa_dataset_path: /srv/datasets/gibson2/data/assetscubicasa_dataset
g_dataset_path: /srv/datasets/gibson2/data/g_dataset
ig_dataset_path: /srv/datasets/gibson2/data/ig_dataset
threedfront_dataset_path: /srv/datasets/gibson2/data/threedfront_dataset
